- name: configure frontend server
  hosts: backend
  become: yes
  tasks:
  - name: Install nginx server
    ansible.builtin.dnf: 
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: niginx
      state: started
      enabled: yes

  - name: delete default website
    ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

